# Generated by Django 2.2.10 on 2020-05-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='abishek@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
